### ISSUE TITLE
Root DNS record gets deleted even if managedRootRecord=false

### ISSUE THREAD

**Issue by jo-me** [containeroo/SyncFlaer#163]
Hi,

I tried out SyncFlaer as replacement for https://github.com/tiredofit/docker-traefik-cloudflare-companion and https://github.com/oznu/docker-cloudflare-ddns.

The first thing Syncflaer did was to delete the root records (A records with my IPs) from CloudFlare.
I intentionally had  `managedRootRecord: false` in the config so that these records are not touched.

As a workaround I had to add additional records in the config to recreate the A records again, but my expectation was that these records are not deleted or overwritten by SyncFlaer. The comment explicitely says: `"set whether you want to have the root record managed by SyncFlaer"`.

Is this a bug?

Jochen

**Comment by rxbn** [comment]
Hi @jo-me

Thanks for creating an issue!

I think the explanation of `managedRootRecord` is incomplete. If you set `managedRootRecord: false`, SyncFlaer will delete the "root" DNS record and not create it automatically. The idea behind that is that you have to manually manage it using `additionalRecords`.

This is because SyncFlaer is designed to be the single source of truth for your A and CNAME DNS records.

I will add some more documentation to that setting.

Your workaround is actually the way to go, when having this setting set to false.

-- Robin

**Comment by jo-me** [comment]
Alright, thanks for clarifying  👍
